runtime: nodejs18
instance_class: F2

env_variables:
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  DATABASE_NAME: "postgres"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: '6\i$U;/_<;pX/_Nr'
  INSTANCE_CONNECTION_NAME: 'e-learning-421208:asia-east1:strapi-education-app'
  GCS_BUCKET_NAME: 'strapi-education-app-bucket'
  GCS_BASE_PATH: 'source'

beta_settings:
  cloud_sql_instances: 'e-learning-421208:asia-east1:strapi-education-app'
