runtime: nodejs18
instance_class: F2

env_variables:
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  DATABASE_NAME: "postgres"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  INSTANCE_CONNECTION_NAME: ${INSTANCE_CONNECTION_NAME}
  GCS_BUCKET_NAME: {$GCS_BUCKET_NAME}
  GCS_BASE_PATH: {$GCS_BASE_PATH}

beta_settings:
  cloud_sql_instances: ${INSTANCE_CONNECTION_NAME}
