steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - "-c"
      - >-
        gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy
        app.yaml --project {$PROJECT_ID}
    env:
      - 'DATABASE_PASSWORD=$_DATABASE_PASSWORD'
      - 'INSTANCE_CONNECTION_NAME=$_INSTANCE_CONNECTION_NAME'
      - 'GCS_BUCKET_NAME=$_GCS_BUCKET_NAME'
      - 'GCS_BASE_PATH=$_GCS_BASE_PATH'
    entrypoint: bash
timeout: 1600s
options:
  logging: CLOUD_LOGGING_ONLY
